<?php
require __DIR__.'/includes/header.php'; $pdo=db(); $id=(int)($_GET['id']??$_POST['checkout_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{ $received=current_user()['full_name']; return_tool($id,$received,$_POST['condition']??'good',trim($_POST['notes']??'')); flash('success','Tool returned successfully.'); redirect('returns.php'); }
 catch(Throwable $e){flash('error',$e->getMessage());redirect('returns.php?id='.$id);}
}
$selected=null;if($id){$s=$pdo->prepare("SELECT c.*,t.tool_name,t.internal_id,t.serial_number,e.name employee_name FROM checkouts c JOIN tools t ON t.id=c.tool_id JOIN employees e ON e.id=c.employee_id WHERE c.id=? AND c.status='open'");$s->execute([$id]);$selected=$s->fetch();}
$rows=$pdo->query("SELECT c.*,t.tool_name,t.internal_id,t.serial_number,e.name employee_name,e.badge_number FROM checkouts c JOIN tools t ON t.id=c.tool_id JOIN employees e ON e.id=c.employee_id WHERE c.status='open' ORDER BY c.checked_out_at")->fetchAll();
?>
<?php if($selected): ?><div class="card"><h2>Return Tool</h2><p><strong><?= e($selected['tool_name']) ?></strong> (<?= e($selected['internal_id']) ?>) issued to <?= e($selected['employee_name']) ?></p><form method="post"><input type="hidden" name="checkout_id" value="<?= $id ?>"><label>Received By</label><input value="<?= e(current_user()['full_name']) ?>" disabled><p class="muted">Recorded from the signed-in account.</p><label>Return Condition</label><select name="condition"><option value="good">Good / Complete</option><option value="missing_parts">Missing Parts</option><option value="damaged">Damaged — Send to Maintenance</option></select><label>Return Notes</label><textarea name="notes"></textarea><div class="actions"><button>Complete Return</button><a class="button secondary" href="returns.php">Cancel</a></div></form></div><?php endif; ?>
<div class="card" style="margin-top:18px"><h2>Tools Awaiting Return</h2><div class="table-wrap"><table><thead><tr><th>Tool</th><th>Employee</th><th>Checked Out</th><th>Due</th><th></th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="5">No open checkouts.</td></tr><?php endif; foreach($rows as $r):$late=strtotime($r['due_at'])<time();?><tr class="<?= $late?'overdue-row':'' ?>"><td><?= e($r['tool_name']) ?><br><span class="muted"><?= e($r['internal_id']) ?> / <?= e($r['serial_number']) ?></span></td><td><?= e($r['employee_name']) ?><br><span class="muted"><?= e($r['badge_number']?:'No badge') ?></span></td><td><?= e(date('M j g:i A',strtotime($r['checked_out_at']))) ?></td><td><span class="badge <?= $late?'overdue':'open' ?>"><?= $late?'OVERDUE':e(date('M j g:i A',strtotime($r['due_at']))) ?></span></td><td><a class="button success" href="returns.php?id=<?= (int)$r['id'] ?>">Return</a></td></tr><?php endforeach;?></tbody></table></div></div>
<?php require __DIR__.'/includes/footer.php'; ?>
