USE tool_rental;
CREATE TABLE IF NOT EXISTS bundles (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,bundle_name VARCHAR(160) NOT NULL,description TEXT NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_bundle_name(bundle_name)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bundle_tools (bundle_id INT UNSIGNED NOT NULL,tool_id INT UNSIGNED NOT NULL,PRIMARY KEY(bundle_id,tool_id),CONSTRAINT fk_bundle_tools_bundle FOREIGN KEY(bundle_id) REFERENCES bundles(id) ON DELETE CASCADE,CONSTRAINT fk_bundle_tools_tool FOREIGN KEY(tool_id) REFERENCES tools(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS accessories (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,accessory_name VARCHAR(160) NOT NULL,internal_id VARCHAR(100) NULL,tool_location VARCHAR(190) NULL,quantity_total INT UNSIGNED NOT NULL DEFAULT 1,quantity_available INT UNSIGNED NOT NULL DEFAULT 1,active TINYINT(1) NOT NULL DEFAULT 1,notes TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_accessory_internal(internal_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS checkout_batches (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,employee_id INT UNSIGNED NOT NULL,issued_by VARCHAR(150) NOT NULL,checked_out_at DATETIME NOT NULL,due_at DATETIME NOT NULL,returned_at DATETIME NULL,received_by VARCHAR(150) NULL,bundle_id INT UNSIGNED NULL,checkout_notes TEXT NULL,return_notes TEXT NULL,status ENUM('open','partial','returned') NOT NULL DEFAULT 'open',CONSTRAINT fk_batch_employee FOREIGN KEY(employee_id) REFERENCES employees(id),CONSTRAINT fk_batch_bundle FOREIGN KEY(bundle_id) REFERENCES bundles(id) ON DELETE SET NULL,INDEX idx_batch_status_due(status,due_at)) ENGINE=InnoDB;
SET @has_batch = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='checkouts' AND COLUMN_NAME='batch_id');
SET @sql = IF(@has_batch=0,'ALTER TABLE checkouts ADD COLUMN batch_id BIGINT UNSIGNED NULL AFTER id, ADD INDEX idx_checkout_batch(batch_id), ADD CONSTRAINT fk_checkout_batch FOREIGN KEY(batch_id) REFERENCES checkout_batches(id) ON DELETE SET NULL','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
CREATE TABLE IF NOT EXISTS checkout_accessories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,batch_id BIGINT UNSIGNED NOT NULL,accessory_id INT UNSIGNED NOT NULL,quantity INT UNSIGNED NOT NULL DEFAULT 1,returned_quantity INT UNSIGNED NOT NULL DEFAULT 0,return_condition ENUM('good','damaged','missing') NULL,returned_at DATETIME NULL,CONSTRAINT fk_checkout_accessory_batch FOREIGN KEY(batch_id) REFERENCES checkout_batches(id) ON DELETE CASCADE,CONSTRAINT fk_checkout_accessory_item FOREIGN KEY(accessory_id) REFERENCES accessories(id),UNIQUE KEY uq_batch_accessory(batch_id,accessory_id)) ENGINE=InnoDB;

-- Convert existing individual checkout records into one-item batches so they remain returnable.
INSERT INTO checkout_batches (employee_id,issued_by,checked_out_at,due_at,returned_at,received_by,checkout_notes,return_notes,status)
SELECT c.employee_id,c.issued_by,c.checked_out_at,c.due_at,c.returned_at,c.received_by,CONCAT('__LEGACY_ID:',c.id,'__',COALESCE(c.checkout_notes,'')),c.return_notes,IF(c.status='returned','returned','open')
FROM checkouts c WHERE c.batch_id IS NULL;
UPDATE checkouts c JOIN checkout_batches b ON b.checkout_notes LIKE CONCAT('__LEGACY_ID:',c.id,'__%') SET c.batch_id=b.id WHERE c.batch_id IS NULL;
UPDATE checkout_batches b JOIN checkouts c ON c.batch_id=b.id SET b.checkout_notes=c.checkout_notes WHERE b.checkout_notes LIKE '__LEGACY_ID:%';
